### ISSUE TITLE
Allow Multiple Descriptions (to support paragraph-style marking)

### ISSUE THREAD

**Issue by johnwunder** [STIXProject/schemas#186]
STIX 1.1.1 contains "Description" fields for many constructs, but these fields are only allowed to appear once. This means that descriptive text must all be marked with the same markings.

This means that it's impossible to some paragraphs in a description more restrictive than others.

A potential workaround is to release several versions of the construct (related together) for the different marking levels.

**Comment by marlontaylor** [comment]
1 How would provides be able to manage/limit the number of descriptions?
2 Would it make sense to require each description to have a unique handling within each element? Otherwise one could end with with multiple "descriptions" of the same handling (possibly with no/conflicting `@ordinality`) within  the same Indicator.
3 If the "otherwise" thought from #2 is desirable, why couldn't or wouldn't one represent the each description within the the single description element that exist today?

**Comment by johnwunder** [comment]
@marlontaylor good questions:

1. I imagine the use case will be limiting it to 0..1 to match STIX 1.2. I have a hard time thinking of a use case where you're OK with 2 descriptions but 3 is too much. Anyway, the ways I could imagine doing this are:
  1. You could limit `@ordinality` values via a profile to a limited number ("1")
  1. Custom schema that restricts `@maxOccurs`
  1. Custom code
1. It's allowed to have two or more descriptions that are marked identically. The idea is that the `@ordinality` attribute will always be unique among a given set of descriptions so you could use that to order the descriptions.
1. You could, but that's not really the use case for multiple descriptions. It's just a side-effect.

**Comment by bschmoker** [comment]
Will update the schemas that reference `Description` (pretty much all of them), then generate a test file and build test to make sure it works sanely
