### ISSUE TITLE
Remove xs:unique contraint on IDs due to issues with timestamps

### ISSUE THREAD

**Issue by johnwunder** [STIXProject/schemas#236]
Right now it will mark different versions of the same `@id` as invalid.

**Comment by bworrell** [comment]
Okie Dokie. I've been playing around with this for a bit and I'm not sure it's totally possible to do this using **just** `<xs:unique>` or `<xs:key>`.

## Existing Uniqueness Constraints

Currently, `@id` uniqueness is enforced by the schema via `<xs:unique>` elements under each of the top-level STIX elements like `STIX_Package` or `Indicator`.

**Example:**
```xml
<xs:unique name="unique-package-id">
	<xs:selector xpath=".//stixCommon:*|.//stix:*|.//cybox:*|.//cyboxCommon:*|.//campaign:*|.//coa:*|.//et:*|.//incident:*|.//indicator:*|.//ta:*|.//ttp:*"/>
	<xs:field xpath="@id"/>
</xs:unique>

```

## Modifying `<xs:unique>` Elements

I had hoped that by adding a `<xs:field xpath="@timestamp">` entry to these `<xs:unique>` elements, I would be able to enforce the uniqueness of an `@id` and `@timestamp` pair. However, it appears that the uniqueness constraint will not raise an error when two STIX components share equal `@id` attribute values, but are missing `@timestamps`. We probably want that to raise validation error, right?

### Example Modifications
The following samples demonstrate my findings.

#### Modified Uniqueness Constraint

The following snippet shows what I changed.

```xml
<xs:unique name="unique-package-id">
	<xs:selector xpath=".//stixCommon:*|.//stix:*|.//cybox:*|.//cyboxCommon:*|.//campaign:*|.//coa:*|.//et:*|.//incident:*|.//indicator:*|.//ta:*|.//ttp:*"/>
	<xs:field xpath="@id"/>

	<!-- ADD THIS FIELD -->
	<xs:field xpath="@timestamp"/>
</xs:unique>
```

#### Example: Uniqueness Violated

The following snippet raises a uniqueness constraint violation error as expected (they share the same `@id` and `@timestamp`)

```xml
<stix:Indicator id="example:indicator-4ec0d699-6daf-4a8a-ac99-4026f5ee33ce" timestamp="2015-03-17T17:11:07.516228+00:00" xsi:type='indicator:IndicatorType'>
    <indicator:Title>Test</indicator:Title>
</stix:Indicator>
<stix:Indicator id="example:indicator-4ec0d699-6daf-4a8a-ac99-4026f5ee33ce" timestamp="2015-03-17T17:11:07.516228+00:00" xsi:type='indicator:IndicatorType'>
    <indicator:Title>Test</indicator:Title>
</stix:Indicator>
```

#### Example: Uniqueness Validated

The following snippet passes schema validation because they have different `@id | @timestamp` pairs (even though they have equal `@id` attributes)

```xml
<stix:Indicator id="example:indicator-4ec0d699-6daf-4a8a-ac99-4026f5ee33ce" timestamp="2015-03-17T17:11:07.516228+00:00" xsi:type='indicator:IndicatorType'>
    <indicator:Title>Test</indicator:Title>
</stix:Indicator>
<stix:Indicator id="example:indicator-4ec0d699-6daf-4a8a-ac99-4026f5ee33ce" timestamp="2015-03-17T17:11:07.516228+00:00" xsi:type='indicator:IndicatorType'>
    <indicator:Title>Test</indicator:Title>
</stix:Indicator>
```

The following snippet passes schema validation because only one defines a `@timestamp`, even though they share equal `@id` attributes.

```xml
<stix:Indicator id="example:indicator-4ec0d699-6daf-4a8a-ac99-4026f5ee33ce" xsi:type='indicator:IndicatorType'>
    <indicator:Title>Test</indicator:Title>
</stix:Indicator>
<stix:Indicator id="example:indicator-4ec0d699-6daf-4a8a-ac99-4026f5ee33ce" timestamp="2015-03-17T17:11:07.516228+00:00"  xsi:type='indicator:IndicatorType'>
    <indicator:Title>Test</indicator:Title>
</stix:Indicator>
```

#### Example: ID Uniquess Lost When Timestamp is Missing

The following snippet **passes** schema validation even though they share equal `@id` attributes and both are missing `@timestamp` values.

```xml
<stix:Indicator id="example:indicator-4ec0d699-6daf-4a8a-ac99-4026f5ee33ce" xsi:type='indicator:IndicatorType'>
    <indicator:Title>Test</indicator:Title>
</stix:Indicator>
<stix:Indicator id="example:indicator-4ec0d699-6daf-4a8a-ac99-4026f5ee33ce" xsi:type='indicator:IndicatorType'>
    <indicator:Title>Test</indicator:Title>
</stix:Indicator>
```


## Further Modifying `<xs:unique>`

I tried to come up with a way of modifying the `<xs:unique>` constraint to trigger if `@timestamp` is missing by selecting `@timestamp | SOME_CONSTANT`, but it doesn't seem to work due to the XPath subset allowed in XML Schema. Selecting `@timestamp | @id` or `@timestamp | .` doesn't work either and triggers errors if an element has both an `@id` and `@timestamp`.

XML Schema only allows a subset of XPath, so I can't write more sophisticated selectors that look for unique IDs among values without timestamps, and look for unique `@id` and `@timestamp` attributes among entities with both timestamps and ids.


## Possible _Solution?_: Default Timestamp

If we use a default timestamp value (e.g., `1970-01-01T00:00:00+00:00`), I think we can enforce `@id` and `@timestamp` uniqueness in schema. There might be something I'm missing, so I'm open to other ideas! Schematron anyone? :)

**Comment by jonathanbaker** [comment]
We will remove the xs:unique in favor of adding python or other validation capabilities.

**Comment by gtback** [comment]
I'll rename the issue :smile:
