### ISSUE TITLE
change readme text w.r.t. releases

### ISSUE THREAD

**Issue by bschmoker** [STIXProject/schemas#300]
[this text](https://github.com/STIXProject/schemas#stix-schema-development)
@gtback  @johnwunder 
Is there a better way to say "You can checkout this tag and get a stable release, or  go to $official_release_site" ?

cc: @STIXProject/owners 

We describe the releases as 'unofficial' [here which feels a bit odd](https://github.com/stixproject/schemas#stix-schema-development)

**Comment by gtback** [comment]
I may be biased, but I like the current language. The releases on GitHub **are** unofficial. 

The I would actually prefer to remove the "releases" entirely, but since we need to keep the tags I don't know if we can. It looks like you can only delete a release via the [API](https://developer.github.com/v3/repos/releases/#delete-a-release)

**Comment by bschmoker** [comment]
Hmm, we could rephrase the 'releases' thing to just say 'All releases are unofficial, refer to $blah to download the production one"

**Comment by bschmoker** [comment]
handled in https://github.com/STIXProject/schemas/commit/141f5cff47aab2985dd7f6e1e2c30b1d1aff81ef
