### ISSUE TITLE
Subclassing Exploit Target

### ISSUE THREAD

**Issue by athiasjerome** [STIXProject/schemas#346]
We could think about extending the Exploit Target by aggregation or subclassing. (for potential use of STIX for Incident Handling)

Example of target enumeration:
target – a computer or network logical entity (account, process, or data) or physical entity
(component, computer, network or internetwork).
e.g.: CybOX includes Accounts objects

Source: Howard, J., Longstaff, T. . “A Common Language For Computer Security Incidents,” Sandia
National Laboratories, Sandia Report, SAND98-8667 1998

**Comment by sbarnum** [comment]
It sounds like what you are proposing would best be explored as extension of Assets within Incident rather than of ExploitTarget. ExploitTarget is intended to characterize specific characteristics (vulnerabilities, weaknesses, configurations) that may make an asset (system, application, person or organization) vulnerable to successful exploitation with security effects but is not intended to characterize the asset itself. In other words, it is not about what assets were targeted in an incident. It is about what sort of characteristics of assets may have been targeted for exploitation. Like TTP/Victim_Targeting this is an abstraction from the concrete specific details of an incident.
I think it likely that when we do refactoring for STIX 2.0 the Asset structure within Incident may get pulled out to a separate structure potentially with some more detail like linking to ExploitTarget so that such details can be clearly expressed for specific Assets. This could serve both an incident response use case as well as an airport situational awareness and preemptive mitigation use case.

**Comment by packet-rat** [comment]
[+1] on 2.0 selection and adoption of an existing framework for assets (that includes effective representation of Virtualized infrastructure)

Patrick Maroney
(609)841-5104

On Jun 12, 2015, at 10:40 AM, sbarnum <notifications@github.com> wrote:

It sounds like what you are proposing would best be explored as extension of Assets within Incident rather than of ExploitTarget. ExploitTarget is intended to characterize specific characteristics (vulnerabilities, weaknesses, configurations) that may make an asset (system, application, person or organization) vulnerable to successful exploitation with security effects but is not intended to characterize the asset itself. In other words, it is not about what assets were targeted in an incident. It is about what sort of characteristics of assets may have been targeted for exploitation. Like TTP/Victim_Targeting this is an abstraction from the concrete specific details of an incident.
I think it likely that when we do refactoring for STIX 2.0 the Asset structure within Incident may get pulled out to a separate structure potentially with some more detail like linking to ExploitTarget so that such details can be clearly expressed for specific Assets. This could serve both an incident response use case as well as an airport situational awareness and preemptive mitigation use case.

**Comment by athiasjerome** [comment]
I agree with @sbarnum comments (I suggest to close this issue and simply reference it in an Asset thread)
