### ISSUE TITLE
Decide on a data format (or multiple data formats) for STIX 2.0

### ISSUE THREAD

**Issue by johnwunder** [STIXProject/schemas#366]
As far as I can tell these are the questions we need to answer:

**1. When should we decide on a data format? Shortly after 2.0 starts, or after we're a good ways in to the abstract model?**

*Arguments for waiting*: it's not the most important topic, some things in the abstract model might not be representable in some formats so we need a better understanding of the model first.  
*Arguments for doing it now*: stop having the discussion every week, people can build prototypes/examples in the final format

**2. Should we allow one format or multiple formats?**

*Arguments for one format*: one way of doing things, better compatibility between products, no translation issues between formats
*Arguments for multiple formats*: translation/compatibility issues are workable via library support, different formats have different pros/cons and may be good for different use cases

**3. What format or formats should we support?**

Some options:
* JSON
* XML
* CapnProto
* Protobuff
* Graph language (Cypher, Gremlin)

**Comment by MarkDavidson** [comment]
Rather than making a decision to either decide now or not, I'd like to see a non-binding shortlist of formats. This will allow prototyping to occur while we evaluate various formats and coordinate the decision across STIX, CybOX, and TAXII.

I offer JSON to the non-binding shortlist.

-Mark

**Comment by wbolster** [comment]
Let me share a few thoughts on the different data formats that pop up in the discussions around the future of STIX/CybOX.

JSON / MessagePack / YAML / CBOR all share the same fundamental "json data model":

* a limited set of primited values (text, numbers, booleans, null)
* two container types: arrays (only values) and mappings (key/value pairs)

...which means they can be transformed into one another relatively easily.

XML on the other hand, is essentially a tree model where each non-text node can have attributes (key/value pairs); this is also known as the "XML infoset". Translation to/from the formats mentioned above is non-trivial and requires various design choices since the underlying models do not match.

Re protobuf and capnproto: these are formats that are closer to the "JSON-like" formats than they are to XML (at least in my experience), but they are specialized for efficiency and performance. The cost of this is that they are not as easy to generate/process (e.g. not self-contained/self-describing, code generation needed, and so on) as simpler formats. I prefer to use these formats only for semi-internal, controlled systems that require tight integration, e.g. an organisation's internal app servers talking to internal backend services.

**Comment by sbarnum** [comment]
I believe this issue has been settled for STIX 2.0

We have voted and approved JSON as the MTI serialization for STIX 2.0.

The STIX 2.0 language data-model/specification will be written in a way to support multiple potential serializations but the MTI JSON serialization will be the only official serialization specified for STIX 2.0.
